/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedMediaRouteImport } from './routes/_protected/media'
import { Route as ProtectedPostsRouteImport } from './routes/_protected/posts'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedPostsIndexRouteImport } from './routes/_protected/posts/index'
import { Route as ProtectedPostsPostIdRouteImport } from './routes/_protected/posts/$postId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as ApiPostsSlugRouteImport } from './routes/api/posts/$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMediaRoute = ProtectedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPostsRoute = ProtectedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedPostsIndexRoute = ProtectedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPostsRoute,
} as any)
const ProtectedPostsPostIdRoute = ProtectedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ProtectedPostsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsSlugRoute = ApiPostsSlugRouteImport.update({
  id: '/api/posts/$slug',
  path: '/api/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof AppLoginRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/media': typeof ProtectedMediaRoute
  '/posts': typeof ProtectedPostsRouteWithChildren
  '/settings': typeof ProtectedSettingsRoute
  '/posts/$postId': typeof ProtectedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/posts/': typeof ProtectedPostsIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AppLoginRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/media': typeof ProtectedMediaRoute
  '/settings': typeof ProtectedSettingsRoute
  '/posts/$postId': typeof ProtectedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/posts': typeof ProtectedPostsIndexRoute
  '/api/posts': typeof ApiPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/media': typeof ProtectedMediaRoute
  '/_protected/posts': typeof ProtectedPostsRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/posts/$postId': typeof ProtectedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$slug': typeof ApiPostsSlugRoute
  '/_protected/posts/': typeof ProtectedPostsIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/media'
    | '/posts'
    | '/settings'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/api/posts/$slug'
    | '/posts/'
    | '/api/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/media'
    | '/settings'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/api/posts/$slug'
    | '/posts'
    | '/api/posts'
  id:
    | '__root__'
    | '/_app'
    | '/_protected'
    | '/_public'
    | '/_app/login'
    | '/_protected/analytics'
    | '/_protected/dashboard'
    | '/_protected/media'
    | '/_protected/posts'
    | '/_protected/settings'
    | '/_public/'
    | '/_protected/posts/$postId'
    | '/api/auth/$'
    | '/api/posts/$slug'
    | '/_protected/posts/'
    | '/api/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPostsSlugRoute: typeof ApiPostsSlugRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/media': {
      id: '/_protected/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof ProtectedMediaRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/posts': {
      id: '/_protected/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ProtectedPostsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/posts/': {
      id: '/_protected/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof ProtectedPostsIndexRouteImport
      parentRoute: typeof ProtectedPostsRoute
    }
    '/_protected/posts/$postId': {
      id: '/_protected/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof ProtectedPostsPostIdRouteImport
      parentRoute: typeof ProtectedPostsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$slug': {
      id: '/api/posts/$slug'
      path: '/api/posts/$slug'
      fullPath: '/api/posts/$slug'
      preLoaderRoute: typeof ApiPostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoginRoute: AppLoginRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProtectedPostsRouteChildren {
  ProtectedPostsPostIdRoute: typeof ProtectedPostsPostIdRoute
  ProtectedPostsIndexRoute: typeof ProtectedPostsIndexRoute
}

const ProtectedPostsRouteChildren: ProtectedPostsRouteChildren = {
  ProtectedPostsPostIdRoute: ProtectedPostsPostIdRoute,
  ProtectedPostsIndexRoute: ProtectedPostsIndexRoute,
}

const ProtectedPostsRouteWithChildren = ProtectedPostsRoute._addFileChildren(
  ProtectedPostsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMediaRoute: typeof ProtectedMediaRoute
  ProtectedPostsRoute: typeof ProtectedPostsRouteWithChildren
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMediaRoute: ProtectedMediaRoute,
  ProtectedPostsRoute: ProtectedPostsRouteWithChildren,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPostsSlugRoute: ApiPostsSlugRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
